image: "python:3.6"

before_script:
  - pip install .
  - pip install -r requirements-dev.txt

stages:
  - test

check-code:
  stage: test
  script: make check

run-test:
  stage: test
  script: pytest